export const EVENTS = {
  TICKET_CREATED: 'TICKET_CREATED',
  AGENT_UPDATED: 'AGENT_UPDATED',
  AGENT_ADDED: 'AGENT_ADDED',
  AGENT_REMOVED: 'AGENT_REMOVED',
  TEAM_UPDATED: 'TEAM_UPDATED',
} as const
